
apiVersion: v1
kind: Service
metadata:
    name: spring-app-service
spec:
    selector:
      app: spring-app
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: spring-app-deployment
spec:
    selector:
      matchLabels:
        app: spring-app
    replicas: 1
    template:
      metadata:
        labels:
          app: spring-app
      spec:
        containers:
          - name: spring-app-container
            image: crudpessoa:1.0
            ports:
              - containerPort: 8080
            env:
              - name: SPRING_DATASOURCE_URL
                value: jdbc:postgresql://postgres-service:5432/crudpessoa
              - name: SPRING_DATASOURCE_USERNAME
                value: myuser
              - name: SPRING_DATASOURCE_PASSWORD
                value: mypassword